version: 2.1

orbs:
  heroku: circleci/heroku@2.0

jobs:
  build-test:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate && pip install -r requirements.txt
      - run: source venv/bin/activate && flake8
      - run: source venv/bin/activate && pytest
  dockerhub:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_TOKEN" | docker login -u="${DOCKER_USER}" --password-stdin
      - run: docker build --tag ${DOCKER_USER}/${CIRCLE_PROJECT}:${CIRCLE_SHA1} .
      - run: docker push ${DOCKER_USER}/${CIRCLE_PROJECT}:${CIRCLE_SHA1}
  deployment:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - build-test
      - dockerhub:
          requires:
            - build-test
          filters:
            branches:
              only:
                - master
      - deployment:
          requires:
            - dockerhub
          filters:
            branches:
              only:
                - master